# .github/workflows/activity.yml
name: Update README with Recent Activity

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  build:
    # --- TAMBAHKAN BLOK INI UNTUK MEMBERIKAN IZIN ---
    permissions:
      contents: write
    # ----------------------------------------------

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://github.com/firdanbash.atom"
